spring.application.name=mon-api
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.security.user.name=admin
spring.security.user.password=secret
spring.jpa.hibernate.ddl-auto=update
# Configuration email (Mailtrap pour le test)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username= e12dafe9357e44
spring.mail.password=456fe079ee4887
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true